- examples/vue-api/main.js
`getRender` wants `createApp` to return `ctx` not `context`, hence the PR.
> vue example: fix context -> ctx

- docs/experimental/data-fetching.md
Small note for TS developers to import *.mjs explicitly.
This is only a minor change to the documentation.
> Small note for TS developers

- packages/fastify-vite/build.js
When the build is done, you rely on another process to exit the code, but it exits the process with an exit code different than 0, which makes the CI process fail.
> fix: exit with status code 0 (no errors) after build is done

- devinstall.mjs
the file uses functions that weren't imported.
also, it used "await" for functions that accept callbacks and do not return promises.
> bugfix: use 'fs/promises' and missing functions

- examples/react-hydration/package.json
- examples/react-hydration/vite.config.js
- examples/react-next/package.json
- examples/react-next/vite.config.js
- examples/react-streaming/package.json
- examples/react-streaming/vite.config.js
- examples/react-vanilla/package.json
- examples/react-vanilla/vite.config.js
- examples/solid-hydration/package.json
- examples/solid-hydration/vite.config.js
- examples/solid-vanilla/package.json
- examples/solid-vanilla/vite.config.js
- examples/svelte-hydration/package.json
- examples/svelte-hydration/vite.config.js
- examples/svelte-vanilla/package.json
- examples/svelte-vanilla/vite.config.js
- examples/vue-hydration/package.json
- examples/vue-hydration/vite.config.js
- examples/vue-next/package.json
- examples/vue-next/vite.config.js
- examples/vue-streaming/package.json
- examples/vue-streaming/vite.config.js
- examples/vue-vanilla/package.json
- examples/vue-vanilla/vite.config.js
- packages/fastify-vite/mode/production.js
These changes are for better windows file system support. 
I changed the build:server script to use "./index.js" as opposed to "/index.js"
I changed the root in the vite.config.js in the example projects to use the relative file path "./client" as windows and *nix systems file paths are different.
I changed the production file to check if it's windows and use the file path instead of the file url if it is. Windows esm loader requires file path.
> fix: issues with Windows file path

- README.md
Hello :),
Just a little PR to fix links in the readme. 
I guess the repo has been renamed but links have not been changed.
Thank you.
> docs(readme): fix links pointing to the repo

- packages/fastify-vite/config.js
`routes` variable is reassigned on line below, so should be let, not const:
https://github.com/fastify/fastify-vite/blob/5170eb62ba54610b8c22fc45c6746cc89b25e7f4/packages/fastify-vite/config.js#L49
> fix(config): assignment to const

- packages/fastify-vite/config.js
This pr solves an issue with loading the vite config in windows
> fix: add windows file check for import in config

- examples/solid-hydration/client/base.jsx
- examples/solid-hydration/client/views/index.jsx
- examples/solid-hydration/client/views/other.jsx
- examples/solid-hydration/package.json
- examples/solid-hydration/renderer.js
- examples/solid-hydration/server.js
- examples/solid-hydration/vite.config.js
- examples/solid-hydration/vitest.config.js
- examples/solid-vanilla/client/mount.js
- examples/solid-vanilla/package.json
- examples/solid-vanilla/server.js
- examples/solid-vanilla/server.test.js
- examples/solid-vanilla/vite.config.js
- examples/solid-vanilla/vitest.config.js
Update `solid-js` examples:
- [solid-hydration](https://github.com/fastify/fastify-vite/tree/dev/examples/solid-hydration)
- [solid-vanilla](https://github.com/fastify/fastify-vite/tree/dev/examples/solid-vanilla)
- Update _dependencies_ and _devDependencies_
- Dependencies:
- Added `@fastify/vite`, `solid-js`
- Removed deprecated `solid-app-router` with `@solidjs/router`
- Removed `@fastify/static`, `fs-extra`, `klaw` because they are already included in `@fastify/vite`
- Added `vite-plugin-solid` (removed from dev dependencies)
- Dev dependencies:
- Added `vitest`
- Added `eslint-plugin-n` peer dependencies of `eslint-config-standard`
- Added `@babel/core` peer dependencies of `@babel/eslint-parser`
- Windows compatibility:
- Replaced `new URL(import.meta.url).pathname` with …
> Update `SolidJS` examples

- packages/fastify-vite/mode/production.js
On Windows system `await exists(serverBundlePath)` is never satisfied when file path is file URL. When converted to URL it works as expected.
> fix: unable to find server bundle on Windows

- packages/fastify-vite/mode/development.js
[Sets vite hmr server to use fastify.](https://vitejs.dev/config/server-options.html#server-hmr:~:text=When%20server.hmr,a%20single%20port.) This fixes #109 and will allow users to use https and h2 with @fastify/vite. Also uses `mergeConfig` and `defineConfig` for hassle free recursive config merging and type safe config declarations.
> fix(hmr): fix hmr when using h2 and use merge config

- docs/react/index.md
This pr fixes the references to React in the documentation. The previous references for `@fastify/react` were incorrect and pointing to Vue.
> docs: fix react references in documentation

- packages/fastify-vite/index.js
There is no named export for the plugin, encountered this when trying to dynamically import the plugin into an ESM file. This change copies the export style of [`@fastify/cookie`](https://github.com/fastify/fastify-cookie/blob/master/plugin.js#L203). I presume that this was not caught by tests because something (Vitest? Node?) is helping with CJS compatibility that masks the problem when running tests.
I have not included tests for this for two reasons, first because it does not seem to be tested for in various other Fastify packages and secondly because the test I produced feels very hacky. I have included it below.
`index.test.mjs`
```js
import { expect, test } from 'vitest'
test('esm - should import plugin dynamically with default and named', async () => {
const FastifyVite = await …
```
> fix: explicitly export named type

- packages/fastify-vite/mode/development.js
When attempting a graceful shutdown, if a page is open with a HMR websocket, it will prevent shutting down. Use the `onClose` hook to shut down the dev server.
> fix: gracefully close open sockets

- examples/react-next/client/pages/items/[id].jsx
- examples/react-next/client/pages/items/index.jsx
- examples/react-next/client/pages/items/nested/[id].jsx
- examples/react-next/renderer.js
Running the react-next example I found out that ky was not available (error: ky is not a function).
I did a refactoring to use fetchJSON in getServerSideProps inside the pages.
Now the example is working.
> fix: use fetchJSON to fix 'ky is not a function' error

- LICENSE
- packages/fastify-htmx/package.json
- packages/fastify-react/package.json
- packages/fastify-vite/package.json
- packages/fastify-vue/package.json
I added repository, keywords, bugs and homepage to package.json files that were missing them for discoverability and better DX.
I added a license file to the root of the repo, so it can be discovered by GitHub. For the copyright statement I was going to include the Fastify Team, but the docs very strongly emphasize that Jonas Galvez is the only maintainer. This matches the copyright statement on the website.
> chore: add LICENSE to repo and fill out missing package.json keys

- packages/fastify-vite/html.test.js
This PR is testing to see if making PRs from my fork repo (rather than another branch in this repo) passes the `agitated-mahavira` CI checks.
> test: Add unit tests for createHtmlTemplateFunction

- packages/fastify-vite/mode/production.js
This PR solves this issue https://github.com/fastify/fastify-vite/issues/162
> fix: Fastify server fail to start in production mode due to: AssertionError [ERR_ASSERTION]: The first character of a path should be `/` or `*`

- packages/fastify-vite/config.js
- packages/fastify-vite/package.json
- packages/fastify-vite/plugin.mjs
- packages/fastify-vite/plugin.test.js
- packages/fastify-vite/sharedPaths.cjs
- packages/fastify-vite/sharedPaths.mjs
Since `find-cache-dir` no longer supports CJS, we can simply change the one file we use it in to a `.mjs` file.
> Convert sharedPaths.cjs to .mjs in order to use latest find-cache-dir

- docs/guide/getting-started.md
- packages/fastify-vite/sharedPaths.mjs
Add some documentation to help developers know how to use with Docker.
> docs: Add note on CACHE_DIR for use in containers like Docker

- .github/workflows/ci.yml
- examples/package.json
- examples/react-hydration/package.json
- examples/react-next/package.json
- examples/react-streaming/package.json
- examples/react-vanilla-spa/package.json
- examples/react-vanilla/package.json
- examples/solid-hydration/package.json
- examples/solid-vanilla/package.json
- examples/svelte-hydration/package.json
- examples/svelte-vanilla/package.json
- examples/typescript-vanilla/package.json
- examples/vue-hydration/package.json
- examples/vue-next/package.json
- examples/vue-streaming/package.json
- examples/vue-vanilla-spa/package.json
- examples/vue-vanilla/package.json
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
This should make it a lot easier to change the versions of dependencies in the examples folder all at once.
> chore: use pnpm catalog feature to dedupe examples' deps

- packages/fastify-vite/mode/production.js
Vite config options `base` can use full URL but node:path join throws AssertionError.
See https://vite.dev/config/shared-options
This changes consider URL and extract pathname.
Since @fastify/vite@6.0.7 occurs.
relates to https://github.com/fastify/fastify-vite/pull/153
> fix: vite.base may be passed full URL but not consider

- starters/htmx-kitchensink/client/views/layout.jsx
I found and fixed a small typo in the `htmx-kichtensink` starter.
> fix(htmx-kitchensink): Typo in <a /> tag (`ree` -> `href`)

- packages/fastify-htmx/plugin.cjs
I noticed that client scripts could not be written in TypeScript since a check was missing in the plugin. This PR fixes that behaviour and TypeScript client scripts are now supported.
There are no tests in `fastify-htmx` yet, so I could not add any. Let me know if you have an idea how to best test this.
> feat(fastify-htmx): allow typescript client files

- packages/fastify-htmx/index.js
I noticed that some client imports where not properly included in vite's output. This was the setup:
`data.tsx`
```ts
import { ListItem } from "../components/ListItem"
export default async function ({ app, req, reply }) {
return (...)
}
```
`../components/ListItem.tsx`
```ts
import type { PropsWithChildren } from "@kitajs/html";
import styles from "./ListItem.module.css";
export function ListItem({ children }: PropsWithChildren) {
return (
<li class={styles.ListItem} safe>
{children}
</li>
);
}
```
`./ListItem.module.css`
```css
.ListItem {
color: red;
}
```
I expected the list items to be red but they were not. Upon further investigation, I noticed that the CSS code from `ListItem.module.css` was generated but not included in the output.
The problem stemmed from this line in `data.tsx`: …
> feat(fastify-htmx): allow for imports without file extensions

- packages/fastify-htmx/index.js
I noticed that failing fastify schemas kept returning `500`s instead of `400`s. After some digging I understood that this default `errorHandler` (from `fastify-vite`) is attached to all routes which overwrites the default fastify error behaviour. 
https://github.com/fastify/fastify-vite/blob/e1ff9414e24051cdab06823aba4e0d256d938f81/packages/fastify-vite/config.js#L93-L101
I was not sure why all errors should be treated as `500`s, this is probably meant as a default error handler that each package should overwrite?
Imo, for `htmx` it makse sense to keep the original fastify error behaviour. This PR adds a custom `createErroHandler` to `fastify-htmx` that logs the error in `dev` mode and in all modes falls back to the default fastify behaviour.
For completeness, here's the code for the …
> fix(fastify-htmx): add proper error handler

- packages/fastify-htmx/index.js
I noticed that CSS from layouts was not being extracted, so I added that functionality to the `prepareClient` method.
The extraction logic takes tries to resolve the specified layout or in case no layout was provided, the `layouts/default` file if one exists. No extra measures are taken when no default layout exists.
In order to speed up builds, I also added the following:
- https://github.com/fastify/fastify-vite/pull/204/commits/3385b580845eb9ae076459182e75e3c5a804a8b5 adds a cache for the layout file resolution
- https://github.com/fastify/fastify-vite/pull/204/commits/839916f94035095748190bd8ed9962fb4277edb7 adds a cache for the client imports
> feat(fastify-htmx): Extract potential layout imports

- .github/workflows/ci.yml
This PR is created by a script. Please check the changes prior to merging.
This PR adds permissions to the workflow and job level, making the workflows read-only by default, and allowing write access only at the job level via granular permissions. This is regularly flagged by CodeQL, Step Security, [OSSF](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions), and other security tools.
This change also allows the org to go read-only everywhere, see https://github.com/fastify/avvio/pull/308#issuecomment-2765300174
> ci: set workflow permissions to read-only by default

- .github/workflows/ci.yml
This PR:
-   Removes Git credentials after checkout as a security precaution by setting `persist-credentials` to false. They are not used after the initial checkout, and this stops them from accidentally leaking through a script; [see related GitHub security post](https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/) and [related actions/checkout issue](https://github.com/actions/checkout/issues/485)
-   Set `check-latest` to true, so that the `actions/setup-node` will check it is using the latest minor or hotfix Node version and use that instead of its cached version, this stops an issue like with 22.5.0 that introduced a regression and actions were still using that instead of 22.5.1
-   Updates actions to their latest major versions; only real change is that …
> ci(ci): update workflow

- docs/contributing.md
- docs/react/router-setup.md
- docs/vue/router-setup.md
- packages/fastify-react/index.js
- packages/fastify-react/plugin.cjs
- packages/fastify-react/virtual/routes.js
- packages/fastify-vue/plugin/virtual.js
- packages/fastify-vue/routing.js
- packages/fastify-vue/server.js
- starters/react-kitchensink/client/pages/index.jsx
- starters/react-kitchensink/client/pages/wildcard/[slug+].jsx
- starters/react-kitchensink/package.json
- starters/vue-base/client/index.html
- starters/vue-kitchensink/client/index.html
- starters/vue-kitchensink/client/pages/index.vue
- starters/vue-kitchensink/client/pages/wildcard/[slug+].vue
- starters/vue-kitchensink/client/root.vue
- starters/vue-kitchensink/package.json
This removes the configurable route parameter regex and sets it to use `[slug]` for singular parameters and `[slug+]` for wildcard routes. This enables routes like `/product-category/[first-slug]/[second-slug]` (and so on) to be matched by a `[slug+].vue` file.
This also enables `catch-all` functionality by placing a `[slug+].vue` file in the client root if you want to dynamically render routes. This also adds a name to the vue routes for `{ name: ... }` routing.
Also fixes the `vue-kitchensink` starter.
**NOTE:** I couldn't get the react-kitchensink starter to work
- [*] run `npm run test` and `npm run benchmark`
- [*] tests and/or benchmarks are included (kitchensink starter)
- [*] documentation is changed or added
- [*] commit message and code follows the [Developer's Certification of …
> feat(vue): wildcard route

- packages/fastify-vite/mode/production.js
Fixes #184 by using `wildcard: false` of `fastify-static` in production, which creates separate routes for each file instead of adding a route for `/*`.
> fix: avoid a wildcard route for serving public files

- packages/fastify-vue/plugin/virtual.js
This fixes the glob (`/pages/**/*.vue`) import paths being prefixed with `../`, e.g. `../C:/Users/Dev/Documents/vue-base/client/pages/index.vue`.
Fixes: #229 
Possibly a rollup/tinyglob bug when using glob inside of a virtual path ($app/routes.js) on Windows. Quite a "hacky fix" (as usual with windows) but I wasn't able to figure out where the actual issue lies.
> fix(vue): glob paths prefix on win32

- package.json
- packages/fastify-vite/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- starters/react-base/package.json
- starters/react-kitchensink/package.json
- starters/react-typescript/package.json
- starters/react-typescript/server.ts
- starters/vue-base/package.json
- starters/vue-kitchensink/package.json
- starters/vue-typescript/package.json
I've added type definitions to the React + TypeScript starter.
I don’t have much experience with `pnpm` and tend to avoid it, since managing type definitions through dependencies can get complicated. We should consider this carefully to avoid future issues.
I suggest opening an issue to address both typing and validation at the same time regarding payloads.
Example in the official demo:
https://github.com/fastify/demo/blob/main/src/routes/api/tasks/index.ts#L22
> fix: add typing for decorators and routes

- packages/fastify-vite/plugin.mjs
Not sure why, but I ran into an issue because there was no `?` here when running `vitest` on CI in one of my projects.
```
TypeError: Cannot read properties of undefined (reading 'outDir')
at file:///builds/path/to/my/repo/node_modules/@fastify/vite/plugin.mjs:72:33
at Array.map (<anonymous>)
at configResolved (file:///builds/path/to/my/repo/node_modules/@fastify/vite/plugin.mjs:71:12)
at file:///builds/path/to/my/repo/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:666[98](https://gitlab.com/path/to/my/repo/-/jobs/9873519651#L98):67
at Array.map (<anonymous>)
at resolveConfig (file:///builds/path/to/my/repo/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66698:53)
at async _createServer (file:///builds/path/to/my/repo/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:63048:18)
at …
```
> fix: question mark

- .github/workflows/ci.yml
closes https://github.com/fastify/fastify-vite/security/code-scanning/25
> ci(ci): pin actions to commit-hash

- .github/workflows/ci.yml
Most first party actions now use https://github.com/actions/publish-immutable-action, which negates the need for commit hashes
> ci: use tags for immutable github actions

- .github/workflows/ci.yml
Add the `--ignore-scripts` arg to disable the execution of any scripts by third-party packages.
See https://snyk.io/blog/npm-security-preventing-supply-chain-attacks/
> ci(ci): ignore scripts

- examples/react-next-mini/renderer.js
- examples/vue-next-mini/renderer.js
- packages/fastify-react/routing.js
- packages/fastify-vue/routing.js
Fixes #292 by returning `reply` object from `async` Fastify handlers where it's missing.\
According to the Fastify [docs](https://fastify.dev/docs/latest/Reference/Routes/#async-await), `reply` must be returned from `async` handler to avoid race conditions.
> fix: return reply in async handlers
