README.md
=> docs: adjust position Rafael Gonzaga

TODO.md
Element-UI is the components library for Vue2.
Element-Plus is the equivalent library for Vue3.
=> todo: replace element ui to element plus

packages/fastify-vite/app.js
I believe it will be slightly better to rest values from the object outside the for-loop since this object exists there.
=> minor improvement: reduce data manipulation

README.md
My open source project made me contribute to fastify-vite.
=> David from Greenpress

docs/quickstart/react.md
Hi!
I noticed that if you're starting a fastify-vite project from scratch using React, you may encounter a couple of errors when following the quickstart guide.
By following the instructions included in this PR, new developers should be able to bootstrap a project with ease.
=> docs: fixed react quickstart instructions in docs

docs/.vitepress/theme/components/CodeBox.vue, docs/.vitepress/theme/components/MarkdownInVue.vue, docs/.vitepress/theme/index.js, docs/experimental/island-mode.md, docs/package.json, docs/quickstart/vue.md
As mentioned in the TODO.md:
Implement select box and click-to-copy like in https://stripe.com/docs/js/initializing
=> feat(docs): Implement select box and click-to-copy

packages/fastify-vite/index.js
regarding this suggestion:
https://github.com/fastify/fastify-vite/issues/66
=> remove fn.call() usage

packages/fastify-vite/mode/development.js
Use optional chaining for client.routes so `spa: true` is usable.
=> fix: client is undefined when spa is true.

packages/fastify-vite/mode/development.js, packages/fastify-vite/package.json
Change deprecated `middie` with `@fastify/middie`.
=> Update middie to @fastify/middie

packages/fastify-vite/package.json
=> chore: add missing fastify-plugin dependency

README.md, packages/fastify-vite/package.json
=> chore!: move `fastify` and `vite` from deps to peerDeps

packages/fastify-vite/index.js
Adds the plugin name to the metadata to allow for dependency checks to be performed.
See https://github.com/fastify/fastify-plugin#name
Don't know if it's also worth adding the dependencies and the fastify version to reflect package.json?
=> chore(index): add plugin metadata

packages/fastify-vite/config.js
=> fix: support defineConfig with callback

packages/fastify-vite/.eslintrc.json, packages/fastify-vite/.eslintrc.yml, packages/fastify-vite/config.js, packages/fastify-vite/package.json, packages/fastify-vite/tsconfig.eslint.json, packages/fastify-vite/types/index.d.ts
Hi everyone!
Thanks for this great plugin ☺️ 
I added a type declaration file and tried to stick to the same style as used in [`@fastify/static`](https://github.com/fastify/fastify-static). For the linting to work I also adapted the ESLint configuration (uses the same as `fastify-static`).
=> Add TypeScript declaration file

packages/fastify-vite/config.js
=> fix: await userConfig to support async vite config

packages/fastify-vite/mode/production.js
=> fix: serve assets from SSR build

packages/fastify-vite/package.json
This is a follow up to #118 to export the newly-added types.d.ts file alongside the main entry point.
=> fix: export types in package.json

docs/.vitepress/config.ts, docs/package.json
=> feat: adds search via Orama

examples/vue-hydration/.eslintrc.yml, examples/vue-vanilla/.eslintrc.yml, package.json, packages/fastify-vite/.eslintrc.json, packages/fastify-vite/package.json, packages/fastify-vite/tsconfig.eslint.json, packages/fastify-vite/tsconfig.json, packages/fastify-vite/types/index.d.ts, packages/fastify-vite/types/index.test-d.ts, packages/fastify-vite/vitest.config.js
just for title,  firstly reference `config.js`. 
=> feat: add more types

docs/react/route-layouts.md, packages/fastify-react/virtual/layouts.js
- Added support tsx extensions for layouts
- Fix docs for @fastify/react layouts
=> fix(react): layouts docs, layout importing code

packages/fastify-vite/config.js, packages/fastify-vite/mode/production.js
=> fix(fastify-vite): file path formats on Windows

starters/react-kitchensink/client/index.html
Addition of:
```<meta name="viewport" content="width=device-width, initial-scale=1.0">```
To prevent viewport to be set at 980px even if it is on mobile, as described here:
[Viewport meta tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag)
=> style: addition of meta in index.html to fix sizing error on mobile

docs/react/router-setup.md
=> docs(react): fix typo

packages/fastify-vite/mode/production.js
=> fix: respect vite.config.js "base" config for production assetsDir

examples/react-hydration/client/index.html, examples/react-next/client/index.html, examples/react-streaming/client/index.html, examples/react-vanilla-spa/client/index.html, examples/react-vanilla/client/index.html, examples/solid-hydration/client/index.html, examples/solid-vanilla/client/index.html, examples/svelte-hydration/client/index.html, examples/svelte-vanilla/client/index.html, examples/vue-hydration/client/index.html, examples/vue-next/client/index.html, examples/vue-streaming/client/index.html, examples/vue-vanilla-spa/client/index.html, examples/vue-vanilla/client/index.html, starters/htmx-base-ts/client/index.html, starters/htmx-base/client/index.html, starters/htmx-kitchensink/client/index.html, starters/react-base/client/index.html, starters/vue-base/client/index.html, starters/vue-kitchensink/client/index.html
Addition of:
<meta name="viewport" content="width=device-width, initial-scale=1.0">
To prevent viewport to be set at 980px even if it is on mobile, as described here:
[Viewport meta tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag)
=> fix: addition of Meta initial scale to all examples and starters inside index.html

examples/react-vanilla/package.json
Same as https://github.com/platformatic/ssr-performance-showdown/pull/7.
Docs would also need to be updated.
Otherwise people are shipping very suboptimal setups with approach recommended by Fastify in its docs.
=> Run React in production mode

packages/fastify-vite/package.json
=> Actually use Fastify v5

packages/fastify-vite/package.json
The current dependencies break with Fastify v5.
=> fix: update package.json to support Fastify v5

packages/fastify-vite/package.json
Looks like the files list in package.json got de-synced during recent refactors.
=> fix: package.json files

examples/react-hydration/vite.config.js, examples/react-next/vite.config.js, examples/react-streaming/vite.config.js, examples/react-vanilla-spa/vite.config.js, examples/react-vanilla/vite.config.js, examples/solid-hydration/vite.config.js, examples/solid-vanilla/vite.config.js, examples/svelte-hydration/vite.config.js, examples/svelte-vanilla/vite.config.js, examples/typescript-vanilla/vite.config.js, examples/vue-hydration/vite.config.js, examples/vue-next/vite.config.js, examples/vue-streaming/vite.config.js, examples/vue-vanilla-spa/vite.config.js, examples/vue-vanilla/vite.config.js
The examples' import paths were incorrect after recent changes.
=> Fix import path of all examples

packages/fastify-vite/package.json
See https://github.com/fastify/fastify/pull/5748
=> build(deps-dev): lock typescript minor version

docs/vue/router-setup.md, packages/fastify-vue/virtual/create.js, starters/vue-kitchensink/client/root.vue
=> feat(vue): allow setting scrollBehavior through :root

docs/react/route-layouts.md, docs/react/route-modules.md
Hey! Found a small problem in the docs and this is a fix for that.
There were two `</script>` tags in the code examples, where they probably should not have been.
Before:
After:
=> fix(docs): remove redundant </script> tags from code examples

docs/guide/getting-started.md
Removes `dirname` import from `node:path` which is not actually used in `vite.config.js`
=> docs: Update getting-started.md

examples/react-vanilla-spa-ts/package.json, examples/react-vanilla-spa-ts/src/client/App.tsx, examples/react-vanilla-spa-ts/src/client/index.html, examples/react-vanilla-spa-ts/src/client/mount.tsx, examples/react-vanilla-spa-ts/src/client/tsconfig.json, examples/react-vanilla-spa-ts/src/server.test.ts, examples/react-vanilla-spa-ts/src/server.ts, examples/react-vanilla-spa-ts/tsconfig.json, examples/react-vanilla-spa-ts/vite.config.js, packages/fastify-vite/plugin.mjs, pnpm-lock.yaml
Looks like we forgot to make sure it works for the SPA use case when providing a `config.build.outDir`. This fixes that.
See the newly added `react-vanilla-spa-ts` example. Without this fix, the location of `vite.config.json` was being sent to `src/client` instead of `build`.
=> fix: spa vite config json

docs/guide/templating-function.md
=> chore(docs): typo in templating-function.md

packages/fastify-htmx/index.js, packages/fastify-htmx/package.json
Removes an unused dependency and bumps two of the dependencies to the neewest version
=> [fastify-htmx] Cleanup dependencies
